name: Compile LaTeX to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Install LaTeX
      run: sudo apt-get install texlive texlive-latex-extra texlive-fonts-recommended

    - name: Compile LaTeX to PDF
      run: |
        pdflatex https://github.com/rahat049/ME4000/blob/main/text.tex
        mv text.pdf $GITHUB_WORKSPACE/text.pdf
